- name: Hello World Sample
  hosts: all
  gather_facts: true
  strategy: debug
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello AWX this playbook comes from github.com/bwalia/ansible-tower-samples!"

    - name: Get whoami information
      sudo: yes
      sudo_user: sciensano
      shell: whoami

    - name: Update all host/vm packages
      ansible.builtin.apt:
              update_cache: true
              cache_valid_time: 3600
              name: "*"
              state: latest

# Add reboot after patching is done.
