- name: Hello World Sample
  hosts: all
  gather_facts: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello AWX this playbook comes from github.com/bwalia/ansible-tower-samples!"

