- name: Host Information
  hosts: all
  become: true
  gather_facts: true
  strategy: debug
  tasks:
    - name: Host IP Information
      debug:
        msg: "IP: {{ sn_ip_address }}"

    - name: Print whoami information
      shell: whoami
