- name: Test Ansible playbook
  hosts: all
  become: true
  gather_facts: true
  strategy: debug
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello AWX this playbook comes from github.com/bwalia/ansible-tower-samples!"

    - name: Get whoami information
      shell: whoami

    - name: Get id information
      shell: id

    # - name: Systemctl list Services
    #   shell: systemctl list-units --type=service

    - name: Systemctl Status SSH
      shell: systemctl status sshd.service
