# SEE ubuntu vm multipass
- name: Ubuntu apply unattended apt updates
  hosts: all
  become: yes
  gather_facts: true
  strategy: debug
  tasks:

    - name: Update Apt cache
      apt:
        update_cache: yes

    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: latest
